# Run Component Governance to register all dependencies.

trigger:
  - main

pool:
  vmImage: "ubuntu-latest"

steps:
  - task: ComponentGovernanceComponentDetection@0
  - task: notice@0
    displayName: 'NOTICE File Generator'
    inputs:
      outputformat: 'text'
